"""Adicionando Itens no Pedido

Revision ID: 49ddccc1fc90
Revises: fadaa0927de6
Create Date: 2025-07-23 17:49:32.392544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ddccc1fc90'
down_revision: Union[str, Sequence[str], None] = 'fadaa0927de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
